### ISSUE TITLE
this is a rat

### ISSUE THREAD

**Issue by idkwhattoget** [TheGuyWhoIsIdiot/rblx15#1]
please fix this huge problem.

**Comment by epicminix** [comment]
By deleting the repo

**Comment by TheGuyWhoIsIdiot** [comment]
> please fix this huge problem.

how is this a rat?

**Comment by TheGuyWhoIsIdiot** [comment]
yk what, no troll comments

**Comment by TheGuyWhoIsIdiot** [comment]
shut up

**Comment by idkwhattoget** [comment]
bro doesnt even know how to disable issues 💀💀💀
